# Generated by Django 6.0.3 on 2026-03-09 04:10

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="EditorSnapshot",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "session_key",
                    models.CharField(db_index=True, max_length=64, unique=True),
                ),
                ("state", models.JSONField()),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
